add some context to the errors for better logs
remove specific error in `sparql_client::new` for better errors.

now a missing prepopulate will be logged as:

```
thread 'main' panicked at 'impossible to search:: impossible to create
client

Caused by:
    0: impossible to create sparql client
    1: impossible to discovery config
    2: No entity with topo id physical_mode found
```